 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(170, 20, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(200, 60, 102, 13))
        self.label_result.setObjectName("label_result")
        self.check_letters = QtWidgets.QCheckBox(self.centralwidget)
        self.check_letters.setGeometry(QtCore.QRect(170, 90, 144, 17))
        self.check_letters.setObjectName("check_letters")
        self.check_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.check_numbers.setGeometry(QtCore.QRect(170, 120, 145, 17))
        self.check_numbers.setObjectName("check_numbers")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_main.setText(_translate("MainWindow", "Генератор паролів "))
        self.label_result.setText(_translate("MainWindow", "Тут буде результат"))
        self.check_letters.setText(_translate("MainWindow", "Використовувати числа"))
        self.check_numbers.setText(_translate("MainWindow", "Використовувати букви"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
